version: "3.9"

services:

  app:
    container_name: planetarium_app
    build: .
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8888:8000
    volumes:
      - .:/app
    restart: always
